name: DIABLO
version: '1.0.0-SNAPSHOT'
main: com.sanctuary.DiabloPlugin
api-version: 1.20
description: "Project Sanctuary - 디아블로 스타일 RPG 엔진"
authors: [Sanctuary Dev Team]
website: https://github.com/sanctuary-project

commands:
  sanctuary:
    description: "Sanctuary 시스템 메인 명령어"
    aliases: [dia, diablo]
    usage: "/sanctuary <reload|status>"
    permission: sanctuary.admin
  combattest:
    description: "전투 시스템 테스트 명령어"
    aliases: [ct]
    usage: "/combattest <stats|setstats|vulnerable|fortify|bleeding|cleardebuffs>"
    permission: sanctuary.admin
  itemtest:
    description: "아이템 시스템 테스트 명령어"
    aliases: [it]
    usage: "/itemtest <give|inspect|tempering|masterwork|demo>"
    permission: sanctuary.admin
  bridgetest:
    description: "네트워크 브릿지 테스트 명령어"
    aliases: [bt]
    usage: "/bridgetest <status|sync|bossbar|damage|hud>"
    permission: sanctuary.admin
  aspecttest:
    description: "위상(Aspect) 시스템 테스트 명령어"
    aliases: [at]
    usage: "/aspecttest <list|add|info|clear>"
    permission: sanctuary.admin
  blacksmith:
    description: "대장간 - 담금질/명품화"
    aliases: [bs, forge]
    usage: "/blacksmith"
    permission: sanctuary.use
  skilltree:
    description: "스킬 트리 관리"
    aliases: [st, skill]
    usage: "/skilltree <info|invest|refund|reset|list|addpoints>"
    permission: sanctuary.use
  paragon:
    description: "정복자 보드 관리"
    aliases: [pg, para]
    usage: "/paragon <info|activate|board|nodes|addpoints|reset>"
    permission: sanctuary.use
  dungeon:
    description: "인스턴스 던전 관리"
    aliases: [dg, dun]
    usage: "/dungeon <create|enter|leave|info|list>"
    permission: sanctuary.use
  helltide:
    description: "지옥물결 관리"
    aliases: [ht]
    usage: "/helltide <start|end|status|zones>"
    permission: sanctuary.admin

permissions:
  sanctuary.admin:
    description: "Sanctuary 관리자 명령어 권한"
    default: op
  sanctuary.use:
    description: "Sanctuary 일반 사용 권한"
    default: true

